theme: jekyll-theme-dinky
title: Lear Adini's Projects
description: Feel free to keep an eye on my projects !
description: All my projects are uploaded to my GitHub repository 
description: I try to give full documentation on each project and what it is doing.
